import 'package:flutter/material.dart';
import '../services/storage_service.dart';

class LanguageProvider with ChangeNotifier {
  String _currentLanguage = 'en'; // 'en', 'ta', 'hi', 'te', 'ml', 'kn'

  String get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadSavedLanguage();
  }

  String get currentLanguageName {
    switch (_currentLanguage) {
      case 'ta':
        return 'Tamil (தமிழ்)';
      case 'hi':
        return 'Hindi (हिन्दी)';
      case 'te':
        return 'Telugu (తెలుగు)';
      case 'ml':
        return 'Malayalam (മലയാളം)';
      case 'kn':
        return 'Kannada (ಕನ್ನಡ)';
      default:
        return 'English (English)';
    }
  }

  Future<void> _loadSavedLanguage() async {
    final saved = await StorageService.getString('app_language');
    if (saved != null && saved.isNotEmpty) {
      _currentLanguage = saved;
      notifyListeners();
    }
  }

  Future<void> setLanguage(String code) async {
    _currentLanguage = code;
    await StorageService.setString('app_language', code);
    notifyListeners();
  }

  // Comprehensive Translation Dictionary
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'SK Technology CCTV',
      'account': 'Account',
      'orders': 'Orders',
      'check_order_status': 'Check your order status',
      'wishlist': 'Wishlist',
      'your_saved_items': 'Your saved items',
      'account_settings': 'Account Settings',
      'saved_addresses': 'Saved Addresses',
      'saved_cards_wallet': 'Saved Cards & Wallet',
      'select_language': 'Select Language',
      'services': 'Services',
      'installation_bookings': 'Installation Bookings',
      'help_center': 'Help Center',
      'refer_earn': 'Refer & Earn',
      'home': 'Home',
      'products': 'Products',
      'service': 'Service',
      'profile': 'Profile',
      'log_in': 'Log In',
      'log_in_exclusive': 'Log in to get exclusive offers',
      'view_cart': 'View Cart',
      'free_delivery': 'Free Delivery',
      'add_to_cart': 'ADD',
      'search_hint': 'Search 27+ CCTV Cameras, DVR...',
      'top_deals': 'Top Deals on Security Tech',
      'trending_now': 'Trending Now',
      'shop_by_category': 'Shop by Category',
      'all': 'All',
      'all_categories': 'All Categories',
      'filters': 'Filters',
      'filter': 'Filter',
      'sort': 'Sort',
      'sort_by': 'Sort By',
      'brand': 'Brand',
      'rating': 'Rating',
      'showing_products': 'Showing products',
      'buy_now': 'Buy Now',
      'items_in_cart': 'Items in Cart',
      'cash_on_delivery': 'Cash on Delivery',
      'pay_after_install': 'Pay After Installation',
      'mega_sale': 'MEGA CCTV SAVINGS SALE',
      'upto_70_off': 'UPTO 70% OFF',
      'sale_ends_in': 'Sale Ends in',
      'explore_now': 'Explore Now',
      'book_installation': 'Book Installation',
      'budget_stores': 'CCTV BUDGET STORES',
      'security_solutions_for_you': 'SECURITY SOLUTIONS FOR YOU',
      'customized_packages': 'Customized CCTV packages tailored by property type',
      'cctv_combo_kits': 'COMPLETE CCTV COMBO KITS',
      'all_in_one_bundles': 'All-in-One Security Bundles with Storage & Free Installation',
      'view_kit': 'View Kit',
      'free_consultation': '100% Free Consultation',
      'need_help_cctv': 'Need Help Choosing the Right CCTV Setup?',
      'free_site_inspection_desc': 'Book a free site inspection. Certified SK CCTV technician will visit your location, check blindspots, and provide best custom quote.',
      'book_free_inspection': 'Book Free Site Inspection in 60s',
      'brand_spotlight': 'BRAND SPOTLIGHT',
      'all_brands': 'ALL BRANDS',
      'order_tracking': 'Order Tracking',
      'total_orders': 'TOTAL ORDERS',
      'in_progress': 'IN PROGRESS',
      'completed': 'COMPLETED',
      'active_amc': 'ACTIVE AMC',
      'login_view_orders': 'Log In to View Your Orders',
      'login_track_desc': 'Please log in to your account to view your live orders and technician tracking timeline.',
      'login_signup': 'Log In / Sign Up',
      'installation_service': 'Installation Service',
      'professional_installation': 'Professional Installation',
      'done_by_experts': 'Done by Experts',
      'our_services': 'Our Services',
      'cctv_installation_title': 'CCTV Installation',
      'cctv_repair_title': 'CCTV Repair & Maintenance',
      'amc_service_title': 'AMC Service',
      'starting_from': 'From',
      'expert_technicians': 'Trained & Certified Technicians',
      'neat_wiring': 'Neat & Professional Wiring',
      'satisfaction_guaranteed': 'Satisfaction Guaranteed',
      'on_time_service': 'On-Time Service',
    },
    'ta': {
      'app_title': 'எஸ்கே டெக்னாலஜி சிசிடிவி',
      'account': 'கணக்கு',
      'orders': 'ஆர்டர்கள்',
      'check_order_status': 'உங்கள் ஆர்டர் நிலையை பார்க்கவும்',
      'wishlist': 'விருப்பப்பட்டியல்',
      'your_saved_items': 'நீங்கள் சேமித்த பொருட்கள்',
      'account_settings': 'கணக்கு அமைப்புகள்',
      'saved_addresses': 'சேமிக்கப்பட்ட முகவரிகள்',
      'saved_cards_wallet': 'கார்டுகள் & பணப்பை',
      'select_language': 'மொழியை தேர்வு செய்',
      'services': 'சேவைகள்',
      'installation_bookings': 'பொருத்துதல் முன்பதிவு',
      'help_center': 'உதவி மையம்',
      'refer_earn': 'பரிந்துரைத்து சம்பாதிக்கவும்',
      'home': 'முகப்பு',
      'products': 'பொருட்கள்',
      'service': 'சேவை',
      'profile': 'சுயவிவரம்',
      'log_in': 'உள்நுழைக',
      'log_in_exclusive': 'சிறப்பு தள்ளுபடிகளுக்கு உள்நுழைக',
      'view_cart': 'கார்ட்டை பார்',
      'free_delivery': 'இலவச டெலிவரி',
      'add_to_cart': 'சேர்',
      'search_hint': 'சிசிடிவி கேமராக்கள், DVR தேடவும்...',
      'top_deals': 'சிறந்த சிசிடிவி தள்ளுபடிகள்',
      'trending_now': 'பிரபலமான தயாரிப்புகள்',
      'shop_by_category': 'வகைகள் வாரியாக',
      'all': 'அனைத்தும்',
      'all_categories': 'அனைத்து வகைகள்',
      'filters': 'வடிகட்டிகள்',
      'filter': 'வடிகட்டி',
      'sort': 'வரிசைப்படுத்து',
      'sort_by': 'வரிசைப்படுத்து',
      'brand': 'பிராண்ட்',
      'rating': 'மதிப்பீடு',
      'showing_products': 'பொருட்கள் காட்டப்படுகின்றன',
      'buy_now': 'இப்போதே வாங்க',
      'items_in_cart': 'கார்ட்டில் உள்ளவை',
      'cash_on_delivery': 'பொருளை பெற்று பணம் செலுத்துங்கள்',
      'pay_after_install': 'பொருத்திய பின் பணம் செலுத்துங்கள்',
      'mega_sale': 'மெகா சிசிடிவி சேமிப்பு விற்பனை',
      'upto_70_off': '70% வரை தள்ளுபடி',
      'sale_ends_in': 'விற்பனை முடிவடைகிறது',
      'explore_now': 'ஆராயுங்கள்',
      'book_installation': 'பொருத்துதலை பதிவு செய்',
      'budget_stores': 'சிசிடிவி பட்ஜெட் ஸ்டோர்',
      'security_solutions_for_you': 'உங்களுக்கான பாதுகாப்பு தீர்வுகள்',
      'customized_packages': 'உங்கள் கட்டிடத்திற்கு ஏற்ற சிசிடிவி தொகுப்புகள்',
      'cctv_combo_kits': 'முழுமையான சிசிடிவி காம்போ கிட்ஸ்',
      'all_in_one_bundles': 'சேமிப்பகம் மற்றும் இலவச பொருத்துதலுடன் கூடிய பாதுகாப்பு தொகுப்புகள்',
      'view_kit': 'தொகுப்பை பார்',
      'free_consultation': '100% இலவச ஆலோசனை',
      'need_help_cctv': 'சரியான சிசிடிவி தேர்வு செய்ய உதவி தேவையா?',
      'free_site_inspection_desc': 'இலவச தள ஆய்வை பதிவு செய்யவும். சான்றளிக்கப்பட்ட தொழில்நுட்ப வல்லுநர் உங்கள் இடத்தை நேரில் பார்வையிட்டு சிறந்த விலையை வழங்குவார்.',
      'book_free_inspection': 'இலவச ஆய்வை பதிவு செய் (60 விநாடி)',
      'brand_spotlight': 'பிரபல பிராண்டுகள்',
      'all_brands': 'அனைத்து பிராண்டுகள்',
      'order_tracking': 'ஆர்டர் கண்காணிப்பு',
      'total_orders': 'மொத்த ஆர்டர்கள்',
      'in_progress': 'செயல்பாட்டில்',
      'completed': 'முடிக்கப்பட்டது',
      'active_amc': 'செயலில் உள்ள AMC',
      'login_view_orders': 'உங்கள் ஆர்டர்களை பார்க்க உள்நுழைக',
      'login_track_desc': 'உங்கள் நேரடி ஆர்டர்களையும் தொழில்நுட்ப வல்லுநரின் நிலையையும் காண உள்நுழைக.',
      'login_signup': 'உள்நுழைக / பதிவு செய்க',
      'installation_service': 'பொருத்துதல் சேவை',
      'professional_installation': 'தொழில்முறை பொருத்துதல்',
      'done_by_experts': 'நிபுணர்களால் செய்யப்படுகிறது',
      'our_services': 'எங்கள் சேவைகள்',
      'cctv_installation_title': 'சிசிடிவி பொருத்துதல்',
      'cctv_repair_title': 'சிசிடிவி பழுதுபார்த்தல் & பராமரிப்பு',
      'amc_service_title': 'AMC பராமரிப்பு சேவை',
      'starting_from': 'இருந்து',
      'expert_technicians': 'சான்றளிக்கப்பட்ட தொழில் வல்லுநர்கள்',
      'neat_wiring': 'நேர்த்தியான தொழில்முறை வயரிங்',
      'satisfaction_guaranteed': '100% திருப்தி உத்தரவாதம்',
      'on_time_service': 'சரியான நேர சேவை',
    },
    'hi': {
      'app_title': 'एसके टेक्नोलॉजी सीसीटीवी',
      'account': 'खाता',
      'orders': 'ऑर्डर',
      'check_order_status': 'अपने ऑर्डर की स्थिति देखें',
      'wishlist': 'विशलिस्ट',
      'your_saved_items': 'आपके सहेजे गए आइटम',
      'account_settings': 'खाता सेटिंग',
      'saved_addresses': 'सहेजे गए पते',
      'saved_cards_wallet': 'कार्ड और वॉलेट',
      'select_language': 'भाषा चुनें',
      'services': 'सेवाएं',
      'installation_bookings': 'इंस्टॉलेशन बुकिंग',
      'help_center': 'सहायता केंद्र',
      'refer_earn': 'रेफर करें और कमाएं',
      'home': 'होम',
      'products': 'उत्पाद',
      'service': 'सेवा',
      'profile': 'प्रोफ़ाइल',
      'log_in': 'लॉग इन करें',
      'log_in_exclusive': 'विशेष छूट के लिए लॉग इन करें',
      'view_cart': 'कार्ट देखें',
      'free_delivery': 'मुफ्त डिलीवरी',
      'add_to_cart': 'जोड़ें',
      'search_hint': 'सीसीटीवी कैमरे, DVR खोजें...',
      'top_deals': 'सिक्योरिटी टेक पर टॉप डील्स',
      'trending_now': 'ट्रेंडिंग उत्पाद',
      'shop_by_category': 'श्रेणी अनुसार',
      'all': 'सभी',
      'all_categories': 'सभी श्रेणियां',
      'filters': 'फ़िल्टर',
      'filter': 'फ़िल्टर',
      'sort': 'क्रमबद्ध',
      'sort_by': 'क्रमबद्ध करें',
      'brand': 'ब्रांड',
      'rating': 'रेटिंग',
      'showing_products': 'उत्पाद दिखाए जा रहे हैं',
      'buy_now': 'अभी खरीदें',
      'items_in_cart': 'कार्ट में आइटम',
      'cash_on_delivery': 'कैश ऑन डिलीवरी',
      'pay_after_install': 'इंस्टॉलेशन के बाद भुगतान',
      'mega_sale': 'मेगा सीसीटीवी बचत सेल',
      'upto_70_off': '70% तक की छूट',
      'sale_ends_in': 'सेल समाप्त होने में',
      'explore_now': 'एक्सप्लोर करें',
      'book_installation': 'इंस्टॉलेशन बुक करें',
      'budget_stores': 'सीसीटीवी बजट स्टोर',
      'security_solutions_for_you': 'आपके लिए सुरक्षा समाधान',
      'customized_packages': 'प्रॉपर्टी के अनुसार कस्टमाइज्ड सीसीटीवी पैकेज',
      'cctv_combo_kits': 'कम्प्लीट सीसीटीवी कॉम्बो किट',
      'all_in_one_bundles': 'स्टोरेज और मुफ्त इंस्टॉलेशन के साथ ऑल-इन-वन सुरक्षा बंडल',
      'view_kit': 'किट देखें',
      'free_consultation': '100% मुफ्त परामर्श',
      'need_help_cctv': 'सही सीसीटीवी सेटअप चुनने में मदद चाहिए?',
      'free_site_inspection_desc': 'मुफ्त साइट निरीक्षण बुक करें। प्रमाणित तकनीशियन आपकी जगह का दौरा करेंगे और सर्वोत्तम कोटेशन देंगे।',
      'book_free_inspection': '60 सेकंड में मुफ्त निरीक्षण बुक करें',
      'brand_spotlight': 'ब्रांड स्पॉटलाइट',
      'all_brands': 'सभी ब्रांड',
      'order_tracking': 'ऑर्डर ट्रैकिंग',
      'total_orders': 'कुल ऑर्डर',
      'in_progress': 'प्रगति में',
      'completed': 'पूर्ण',
      'active_amc': 'सक्रिय AMC',
      'login_view_orders': 'अपने ऑर्डर देखने के लिए लॉग इन करें',
      'login_track_desc': 'अपने लाइव ऑर्डर और तकनीशियन ट्रैकिंग टाइमलाइन देखने के लिए लॉग इन करें।',
      'login_signup': 'लॉग इन / साइन अप',
      'installation_service': 'इंस्टॉलेशन सेवा',
      'professional_installation': 'पेशेवर इंस्टॉलेशन',
      'done_by_experts': 'विशेषज्ञों द्वारा किया गया',
      'our_services': 'हमारी सेवाएं',
      'cctv_installation_title': 'सीसीटीवी इंस्टॉलेशन',
      'cctv_repair_title': 'सीसीटीवी मरम्मत और रखरखाव',
      'amc_service_title': 'एएमसी सेवा',
      'starting_from': 'शुरुआती',
      'expert_technicians': 'प्रशिक्षित और प्रमाणित तकनीशियन',
      'neat_wiring': 'साफ और पेशेवर वायरिंग',
      'satisfaction_guaranteed': 'संतुष्टि की गारंटी',
      'on_time_service': 'समय पर सेवा',
    },
    'te': {
      'app_title': 'ఎస్కే టెక్నాలజీ సీసీటీవీ',
      'account': 'ఖాతా',
      'orders': 'ఆర్డర్లు',
      'check_order_status': 'ఆర్డర్ స్థితిని తనిఖీ చేయండి',
      'wishlist': 'కోరికల జాబితా',
      'your_saved_items': 'మీరు సేవ్ చేసినవి',
      'account_settings': 'ఖాతా సెట్టింగ్‌లు',
      'saved_addresses': 'చిరునామాలు',
      'saved_cards_wallet': 'కార్డులు & వాలెట్',
      'select_language': 'భాషను ఎంచుకోండి',
      'services': 'సేవలు',
      'installation_bookings': 'ఇన్‌స్టాలేషన్ బుకింగ్స్',
      'help_center': 'సహాయ కేంద్రం',
      'refer_earn': 'రిఫర్ చేయండి & సంపాదించండి',
      'home': 'హోమ్',
      'products': 'ఉత్పత్తులు',
      'service': 'సర్వీస్',
      'profile': 'ప్రొఫైల్',
      'log_in': 'లాగిన్ చేయండి',
      'log_in_exclusive': 'ప్రత్యేక ఆఫర్ల కోసం లాగిన్ చేయండి',
      'view_cart': 'కార్ట్ చూడండి',
      'free_delivery': 'ఉచిత డెలివరీ',
      'add_to_cart': 'జోడించు',
      'search_hint': 'సీసీటీవీ కెమెరాలు, DVR శోధించండి...',
      'top_deals': 'టాప్ డీల్స్',
      'trending_now': 'ట్రెండింగ్ ఉత్పత్తులు',
      'shop_by_category': 'కేటగిరీల వారీగా',
      'all': 'అన్నీ',
      'all_categories': 'అన్ని వర్గాలు',
      'filters': 'ఫిల్టర్లు',
      'filter': 'ఫిల్టర్',
      'sort': 'క్రమబద్ధీకరించు',
      'sort_by': 'క్రమబద్ధీకరించు',
      'brand': 'బ్రాండ్',
      'rating': 'రేటింగ్',
      'showing_products': 'ఉత్పత్తులు చూపబడుతున్నాయి',
      'buy_now': 'ఇప్పుడే కొనండి',
      'items_in_cart': 'కార్ట్‌లోని అంశాలు',
      'cash_on_delivery': 'క్యాష్ ఆన్ డెలివరీ',
      'pay_after_install': 'ఇన్‌స్టాలేషన్ తర్వాత చెల్లించండి',
      'mega_sale': 'మెగా సీసీటీవీ సేవింగ్స్ సేల్',
      'upto_70_off': '70% వరకు తగ్గింపు',
      'sale_ends_in': 'సేల్ ముగింపు',
      'explore_now': 'ఎక్స్‌ప్లోర్ చేయండి',
      'book_installation': 'ఇన్‌స్టాలేషన్ బుక్ చేయండి',
      'budget_stores': 'సీసీటీవీ బడ్జెట్ స్టోర్స్',
      'security_solutions_for_you': 'మీ కోసం భద్రతా పరిష్కారాలు',
      'customized_packages': 'కస్టమైజ్డ్ సీసీటీవీ ప్యాకేజీలు',
      'cctv_combo_kits': 'పూర్తి సీసీటీవీ కాంబో కిట్‌లు',
      'all_in_one_bundles': 'స్టోరేజ్ మరియు ఉచిత ఇన్‌స్టాలేషన్‌తో ఆల్-ఇన్-వన్ భద్రతా బండిల్స్',
      'view_kit': 'కిట్ చూడండి',
      'free_consultation': '100% ఉచిత సంప్రదింపులు',
      'need_help_cctv': 'సరైన సీసీటీవీ సెటప్ ఎంచుకోవడంలో సహాయం కావాలా?',
      'free_site_inspection_desc': 'ఉచిత సైట్ తనిఖీని బుక్ చేయండి. సర్టిఫైడ్ టెక్నీషియన్ మీ స్థలాన్ని సందర్శించి ఉత్తమ కొటేషన్ ఇస్తారు.',
      'book_free_inspection': 'ఉచిత తనిఖీని బుక్ చేయండి',
      'brand_spotlight': 'బ్రాండ్ స్పాట్‌లైట్',
      'all_brands': 'అన్ని బ్రాండ్లు',
      'order_tracking': 'ఆర్డర్ ట్రాకింగ్',
      'total_orders': 'మొత్తం ఆర్డర్లు',
      'in_progress': 'పురోగతిలో ఉంది',
      'completed': 'పూర్తయింది',
      'active_amc': 'యాక్టివ్ AMC',
      'login_view_orders': 'మీ ఆర్డర్లను చూడటానికి లాగిన్ చేయండి',
      'login_track_desc': 'మీ లైవ్ ఆర్డర్లు మరియు టెక్నీషియన్ ట్రాకింగ్ కోసం లాగిన్ అవ్వండి.',
      'login_signup': 'లాగిన్ / సైన్ అప్',
      'installation_service': 'ఇన్‌స్టాలేషన్ సర్వీస్',
      'professional_installation': 'ప్రొఫెషనల్ ఇన్‌స్టాలేషన్',
      'done_by_experts': 'నిపుణులచే చేయబడుతుంది',
      'our_services': 'మా సేవలు',
      'cctv_installation_title': 'సీసీటీవీ ఇన్‌స్టాలేషన్',
      'cctv_repair_title': 'సీసీటీవీ రిపేర్ & మెయింటెనెన్స్',
      'amc_service_title': 'AMC సర్వీస్',
      'starting_from': 'నుండి',
      'expert_technicians': 'శిక్షణ పొందిన నిపుణులు',
      'neat_wiring': 'నీట్ ప్రొఫెషనల్ వైరింగ్',
      'satisfaction_guaranteed': '100% సంతృప్తి హామీ',
      'on_time_service': 'సమయానికి సేవ',
    },
    'ml': {
      'app_title': 'എസ്കെ ടെക്നോളജി സിസിടിവി',
      'account': 'അക്കൗണ്ട്',
      'orders': 'ഓർഡറുകൾ',
      'check_order_status': 'ഓർഡർ നില പരിശോധിക്കുക',
      'wishlist': 'വിഷ് ലിസ്റ്റ്',
      'your_saved_items': 'സേവ് ചെയ്തവ',
      'account_settings': 'ക്രമീകരണങ്ങൾ',
      'saved_addresses': 'വിലാസങ്ങൾ',
      'saved_cards_wallet': 'കാർഡുകളും വാലറ്റും',
      'select_language': 'ഭാഷ മാറ്റുക',
      'services': 'സേവനങ്ങൾ',
      'installation_bookings': 'ഇൻസ്റ്റാളേഷൻ ബുക്കിംഗ്',
      'help_center': 'സഹായ കേന്ദ്രം',
      'refer_earn': 'റഫർ ചെയ്ത് നേടാം',
      'home': 'ഹോം',
      'products': 'ഉൽപ്പന്നങ്ങൾ',
      'service': 'സർവീസ്',
      'profile': 'പ്രൊഫൈൽ',
      'log_in': 'ലോഗിൻ',
      'log_in_exclusive': 'ഓഫറുകൾക്കായി ലോഗിൻ ചെയ്യുക',
      'view_cart': 'കാർട്ട് കാണുക',
      'free_delivery': 'സൗജന്യ ഡെലിവറി',
      'add_to_cart': 'ചേർക്കുക',
      'search_hint': 'സിസിടിവി ക്യാമറകൾ തിരയുക...',
      'top_deals': 'പ്രത്യേക ഓഫറുകൾ',
      'trending_now': 'ട്രെൻഡിംഗ് ഉൽപ്പന്നങ്ങൾ',
      'shop_by_category': 'വിഭാഗങ്ങൾ',
      'all': 'എല്ലാം',
      'all_categories': 'എല്ലാ വിഭാഗങ്ങളും',
      'filters': 'ഫിൽട്ടറുകൾ',
      'filter': 'ഫിൽട്ടർ',
      'sort': 'ക്രമീകരിക്കുക',
      'sort_by': 'ക്രമീകരിക്കുക',
      'brand': 'ബ്രാൻഡ്',
      'rating': 'റേറ്റിംഗ്',
      'showing_products': 'ഉൽപ്പന്നങ്ങൾ കാണിക്കുന്നു',
      'buy_now': 'വാങ്ങുക',
      'items_in_cart': 'കാർട്ടിലുള്ളവ',
      'cash_on_delivery': 'ക്യാഷ് ഓൺ ഡെലിവറി',
      'pay_after_install': 'ഇൻസ്റ്റാളേഷന് ശേഷം പണം',
      'mega_sale': 'മെഗാ സിസിടിവി സേവിംഗ്സ് സെയിൽ',
      'upto_70_off': '70% വരെ കിഴിവ്',
      'sale_ends_in': 'സെയിൽ അവസാനിക്കാൻ',
      'explore_now': 'കാണുക',
      'book_installation': 'ഇൻസ്റ്റാളേഷൻ ബുക്ക് ചെയ്യുക',
      'budget_stores': 'സിസിടിവി ബഡ്ജറ്റ് സ്റ്റോറുകൾ',
      'security_solutions_for_you': 'നിങ്ങൾക്കായുള്ള സുരക്ഷാ പാക്കേജുകൾ',
      'customized_packages': 'പ്രോപ്പർട്ടി അനുയോജ്യമായ പാക്കേജുകൾ',
      'cctv_combo_kits': 'സിസിടിവി കോംബോ കിറ്റുകൾ',
      'all_in_one_bundles': 'സ്റ്റോറേജും സൗജന്യ ഇൻസ്റ്റാളേഷനുമുള്ള സുരക്ഷാ ബണ്ടിലുകൾ',
      'view_kit': 'കിറ്റ് കാണുക',
      'free_consultation': '100% സൗജന്യ കൺസൾട്ടേഷൻ',
      'need_help_cctv': 'ശരിയായ സിസിടിവി തിരഞ്ഞെടുക്കാൻ സഹായം വേണോ?',
      'free_site_inspection_desc': 'സൗജന്യ സൈറ്റ് പരിശോധന ബുക്ക് ചെയ്യുക. സർട്ടിഫൈഡ് ടെക്നീഷ്യൻ നിങ്ങളുടെ സ്ഥലം സന്ദർശിച്ച് മികച്ച കൊട്ടേഷൻ നൽകും.',
      'book_free_inspection': 'സൗജന്യ പരിശോധന ബുക്ക് ചെയ്യുക',
      'brand_spotlight': 'ബ്രാൻഡ് സ്പോട്ട്‌ലൈറ്റ്',
      'all_brands': 'എല്ലാ ബ്രാൻഡുകളും',
      'order_tracking': 'ഓർഡർ ട്രാക്കിംഗ്',
      'total_orders': 'ആകെ ഓർഡറുകൾ',
      'in_progress': 'നടന്നുകൊണ്ടിരിക്കുന്നു',
      'completed': 'പൂർത്തിയായി',
      'active_amc': 'സജീവ AMC',
      'login_view_orders': 'ഓർഡറുകൾ കാണാൻ ലോഗിൻ ചെയ്യുക',
      'login_track_desc': 'ലൈവ് ഓർഡറുകളും ടെക്നീഷ്യൻ ട്രാക്കിംഗും കാണാൻ ലോഗിൻ ചെയ്യുക.',
      'login_signup': 'ലോഗിൻ / സൈൻ അപ്പ്',
      'installation_service': 'ഇൻസ്റ്റാളേഷൻ സർവീസ്',
      'professional_installation': 'പ്രൊഫഷണൽ ഇൻസ്റ്റാളേഷൻ',
      'done_by_experts': 'വിദഗ്ദ്ധർ ചെയ്യുന്നു',
      'our_services': 'ഞങ്ങളുടെ സേവനങ്ങൾ',
      'cctv_installation_title': 'സിസിടിവി ഇൻസ്റ്റാളേഷൻ',
      'cctv_repair_title': 'സിസിടിവി റിപ്പയർ & മെയിന്റനൻസ്',
      'amc_service_title': 'AMC സർവീസ്',
      'starting_from': 'മുതൽ',
      'expert_technicians': 'പരിശീലനം ലഭിച്ച വിദഗ്ദ്ധർ',
      'neat_wiring': 'വ്യത്തിയുള്ള പ്രൊഫഷണൽ വയറിംഗ്',
      'satisfaction_guaranteed': '100% തൃപ്തി ഉറപ്പ്',
      'on_time_service': 'കൃത്യസമയത്തുള്ള സേവനം',
    },
    'kn': {
      'app_title': 'ಎಸ್ಕೆ ಟೆಕ್ನಾಲಜಿ ಸಿಸಿಟಿವಿ',
      'account': 'ಖಾತೆ',
      'orders': 'ಆರ್ಡರ್‌ಗಳು',
      'check_order_status': 'ನಿಮ್ಮ ಆರ್ಡರ್ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
      'wishlist': 'ವಿಶ್‌ಲಿಸ್ಟ್',
      'your_saved_items': 'ಉಳಿಸಿದವುಗಳು',
      'account_settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'saved_addresses': 'ವಿಳಾಸಗಳು',
      'saved_cards_wallet': 'ಕಾರ್ಡ್‌ಗಳು & ವಾಲೆಟ್',
      'select_language': 'ಭಾಷೆ ಬದಲಿಸಿ',
      'services': 'ಸೇವೆಗಳು',
      'installation_bookings': 'ಸ್ಥಾಪನೆ ಬುಕಿಂಗ್‌ಗಳು',
      'help_center': 'ಸಹಾಯ ಕೇಂದ್ರ',
      'refer_earn': 'ರೆಫರ್ ಮಾಡಿ ಗಳಿಸಿ',
      'home': 'ಮುಖಪುಟ',
      'products': 'ಉತ್ಪನ್ನಗಳು',
      'service': 'ಸೇವೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'log_in': 'ಲಾಗಿನ್',
      'log_in_exclusive': 'ಆಫರ್‌ಗಳಿಗಾಗಿ ಲಾಗಿನ್ ಮಾಡಿ',
      'view_cart': 'ಕಾರ್ಟ್ ನೋಡಿ',
      'free_delivery': 'ಉಚಿತ ಡೆಲಿವರಿ',
      'add_to_cart': 'ಸೇರಿಸಿ',
      'search_hint': 'ಸಿಸಿಟಿವಿ ಕ್ಯಾಮೆರಾಗಳು ಹುಡುಕಿ...',
      'top_deals': 'ಟಾಪ್ ಡೀಲ್‌ಗಳು',
      'trending_now': 'ಟ್ರೆಂಡಿಂಗ್ ಉತ್ಪನ್ನಗಳು',
      'shop_by_category': 'ವರ್ಗಗಳು',
      'all': 'ಎಲ್ಲಾ',
      'all_categories': 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
      'filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
      'filter': 'ಫಿಲ್ಟರ್',
      'sort': 'ವಿಂಗಡಿಸಿ',
      'sort_by': 'ವಿಂಗಡಿಸಿ',
      'brand': 'ಬ್ರಾಂಡ್',
      'rating': 'ರೇಟಿಂಗ್',
      'showing_products': 'ಉತ್ಪನ್ನಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ',
      'buy_now': 'ಈಗಲೇ ಖರೀದಿಸಿ',
      'items_in_cart': 'ಕಾರ್ಟ್‌ನಲ್ಲಿರುವ ಐಟಂಗಳು',
      'cash_on_delivery': 'ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ',
      'pay_after_install': 'ಸ್ಥಾಪನೆಯ ನಂತರ ಪಾವತಿ',
      'mega_sale': 'ಮೆಗಾ ಸಿಸಿಟಿವಿ ಸೇವಿಂಗ್ಸ್ ಸೇಲ್',
      'upto_70_off': '70% ವರೆಗೆ ರಿಯಾಯಿತಿ',
      'sale_ends_in': 'ಸೇಲ್ ಮುಕ್ತಾಯ',
      'explore_now': 'ವೀಕ್ಷಿಸಿ',
      'book_installation': 'ಸ್ಥಾಪನೆ ಬುಕ್ ಮಾಡಿ',
      'budget_stores': 'ಸಿಸಿಟಿವಿ ಬಜೆಟ್ ಸ್ಟೋರ್‌ಗಳು',
      'security_solutions_for_you': 'ನಿಮಗಾಗಿ ಭದ್ರತಾ ಪರಿಹಾರಗಳು',
      'customized_packages': 'ಕಸ್ಟಮೈಸ್ಡ್ ಸಿಸಿಟಿವಿ ಪ್ಯಾಕೇಜ್‌ಗಳು',
      'cctv_combo_kits': 'ಸಂಪೂರ್ಣ ಸಿಸಿಟಿವಿ ಕಾಂಬೋ ಕಿಟ್‌ಗಳು',
      'all_in_one_bundles': 'ಶೇಖರಣೆ ಮತ್ತು ಉಚಿತ ಸ್ಥಾಪನೆಯೊಂದಿಗೆ ಭದ್ರತಾ ಬಂಡಲ್‌ಗಳು',
      'view_kit': 'ಕಿಟ್ ವೀಕ್ಷಿಸಿ',
      'free_consultation': '100% ಉಚಿತ ಸಮಾಲೋಚನೆ',
      'need_help_cctv': 'ಸರಿಯಾದ ಸಿಸಿಟಿವಿ ಸೆಟಪ್ ಆಯ್ಕೆ ಮಾಡಲು ಸಹಾಯ ಬೇಕೇ?',
      'free_site_inspection_desc': 'ಉಚಿತ ಸೈಟ್ ಪರಿಶೀಲನೆ ಬುಕ್ ಮಾಡಿ. ಪ್ರಮಾಣೀಕೃತ ತಜ್ಞರು ನಿಮ್ಮ ಸ್ಥಳಕ್ಕೆ ಭೇಟಿ ನೀಡಿ ಉತ್ತಮ ಕೊಟೇಶನ್ ನೀಡುತ್ತಾರೆ.',
      'book_free_inspection': 'ಉಚಿತ ಪರಿಶೀಲನೆ ಬುಕ್ ಮಾಡಿ',
      'brand_spotlight': 'ಬ್ರಾಂಡ್ ಸ್ಪಾಟ್‌ಲೈಟ್',
      'all_brands': 'ಎಲ್ಲಾ ಬ್ರಾಂಡ್‌ಗಳು',
      'order_tracking': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್',
      'total_orders': 'ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು',
      'in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
      'active_amc': 'ಸಕ್ರಿಯ AMC',
      'login_view_orders': 'ಆರ್ಡರ್‌ಗಳನ್ನು ನೋಡಲು ಲಾಗಿನ್ ಮಾಡಿ',
      'login_track_desc': 'ನಿಮ್ಮ ಲೈವ್ ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಟೆಕ್ನಿಷಿಯನ್ ಟ್ರ್ಯಾಕಿಂಗ್‌ಗಾಗಿ ಲಾಗಿನ್ ಮಾಡಿ.',
      'login_signup': 'ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್',
      'installation_service': 'ಸ್ಥಾಪನೆ ಸೇವೆ',
      'professional_installation': 'ವೃತ್ತಿಪರ ಸ್ಥಾಪನೆ',
      'done_by_experts': 'ತಜ್ಞರಿಂದ ಮಾಡಲಾಗುತ್ತದೆ',
      'our_services': 'ನಮ್ಮ ಸೇವೆಗಳು',
      'cctv_installation_title': 'ಸಿಸಿಟಿವಿ ಸ್ಥಾಪನೆ',
      'cctv_repair_title': 'ಸಿಸಿಟಿವಿ ದುರಸ್ತಿ ಮತ್ತು ನಿರ್ವಹಣೆ',
      'amc_service_title': 'AMC ಸೇವೆ',
      'starting_from': 'ಇಂದ',
      'expert_technicians': 'ತರಬೇತಿ ಪಡೆದ ತಜ್ಞರು',
      'neat_wiring': 'ಅಚ್ಚುಕಟ್ಟಾದ ವೈರಿಂಗ್',
      'satisfaction_guaranteed': '100% ತೃಪ್ತಿ ಖಾತರಿ',
      'on_time_service': 'ಸಮಯಕ್ಕೆ ಸೇವೆ',
    },
  };

  String tr(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
